"""
LangGraph State Definition
Define the global state structure for the data cleaning Agent
"""
from typing import TypedDict, Optional, Dict, Any, List
from typing_extensions import Annotated
import operator


class DataCleaningState(TypedDict):
    """
    Global state for the data cleaning Agent

    State flow path:
    Profiler -> Coder -> Executor -> QA -> END
                  ^                  |
                  |__________________|  (Self-Correction Loop)
    """

    # ========== Original Data Information ==========
    original_df_info: Dict[str, Any]
    """
    Metadata information of the original DataFrame
    Contains:
    - shape: (rows, cols)
    - columns: list of column names
    - dtypes: dictionary of column types
    - null_counts: null value statistics
    - sample_data: first 10 rows of data (as string)
    - memory_usage: memory consumption
    """

    # ========== Cleaning Strategy ==========
    cleaning_plan: Optional[str]
    """
    Cleaning strategy generated by Profiler Node
    Format: Markdown text, containing:
    1. Data quality problem diagnosis
    2. Cleaning step planning
    3. Expected output
    """

    # ========== Code Generation ==========
    generated_code: Optional[str]
    """
    Pandas cleaning code generated by Coder Node
    Format: Python code string
    Requirements:
    - Input variable name fixed as df
    - Output variable name fixed as cleaned_df
    - Contains detailed comments
    """

    # ========== Execution Results ==========
    execution_error: Optional[str]
    """
    Error information during code execution
    - None: execution succeeded
    - str: Traceback error message (used for Self-Correction)
    """

    execution_success: bool
    """
    Flag indicating whether code execution succeeded
    - True: execution succeeded, can proceed to QA Node
    - False: execution failed, need to regenerate code
    """

    # ========== Retry Control ==========
    retry_count: Annotated[int, operator.add]
    """
    Code generation retry counter
    - Initial value: 0
    - Increments by 1 each time entering Self-Correction Loop
    - Limit: 3 (forced termination if exceeded)
    Uses Annotated[int, operator.add] to implement accumulation semantics
    """

    # ========== Cleaned Data Information ==========
    cleaned_df_info: Optional[Dict[str, Any]]
    """
    Metadata information of the cleaned DataFrame
    Structure same as original_df_info
    Used by QA Node for before/after comparison
    """

    # ========== QA Results ==========
    qa_result: Optional[Dict[str, Any]]
    """
    Quality assurance results
    Contains:
    - passed: bool, whether QA passed
    - issues: List[str], list of discovered issues
    - metrics: Dict, quality metrics (e.g., missing rate, duplication rate)
    """

    # ========== Data Paths ==========
    input_file_path: str
    """File path of input dirty data"""

    output_file_path: str
    """Output path of cleaned data"""

    # ========== EDA Related ==========
    eda_plan: Optional[str]
    """
    Plotting scheme and insights generated by EDA Node
    Format: Markdown text, containing business insights about the data
    """

    eda_code: Optional[str]
    """
    Plotting Python code generated by EDA Node
    Format: Python code string
    Requirements:
    - Contains generate_plots(df, output_dir) function
    - Uses seaborn/matplotlib to generate visualizations
    - 100% pure English (no Emoji, no Chinese)
    """

    eda_error: Optional[str]
    """
    Error information during EDA code execution
    - None: execution succeeded
    - str: Traceback error message
    """

    # ========== History Records (Optional, for debugging) ==========
    execution_history: Annotated[List[Dict[str, Any]], operator.add]
    """
    Execution history record list
    Each execution appends a record:
    {
        "attempt": int,
        "code": str,
        "error": Optional[str],
        "timestamp": str
    }
    Uses Annotated[List, operator.add] to implement list appending
    """


class StateFactory:
    """State factory class for creating initial state"""

    @staticmethod
    def create_initial_state(
        input_file_path: str,
        output_file_path: str = "outputs/cleaned_data.csv"
    ) -> DataCleaningState:
        """
        Create initial state

        Args:
            input_file_path: Input dirty data file path
            output_file_path: Output cleaned data file path

        Returns:
            Initialized DataCleaningState
        """
        return {
            "original_df_info": {},
            "cleaning_plan": None,
            "generated_code": None,
            "execution_error": None,
            "execution_success": False,
            "retry_count": 0,
            "cleaned_df_info": None,
            "qa_result": None,
            "input_file_path": input_file_path,
            "output_file_path": output_file_path,
            "eda_plan": None,
            "eda_code": None,
            "eda_error": None,
            "execution_history": []
        }
