"""
Executor Node - Code Execution Node

Responsibilities:
    Act as a "sandbox" to safely execute code generated by Coder
    Capture execution errors to form Self-Correction feedback loop
"""
import traceback
from typing import Dict, Any
import pandas as pd
from pathlib import Path

from ..core.state import DataCleaningState


# ========== Node Function ==========
def executor_node(state: DataCleaningState) -> Dict[str, Any]:
    """
    Executor Node - Code Execution Node

    Functions:
        1. Read dirty data CSV
        2. Execute generated code in isolated namespace
        3. Extract clean_data function and execute
        4. Save cleaned data
        5. Capture exceptions and update state

    Args:
        state: Global state object

    Returns:
        Dictionary containing updated fields:
        - execution_success: Whether execution succeeded
        - execution_error: Error message (None if succeeded)
        - cleaned_df_info: Cleaned data metadata (if succeeded)
        - execution_history: Execution history (appended)
    """
    print("\n" + "="*60)
    print("[Executor Node] Starting code execution...")
    print("="*60)

    # 1. Read inputs
    generated_code = state.get("generated_code")
    input_file_path = state.get("input_file_path")
    output_file_path = state.get("output_file_path")
    retry_count = state.get("retry_count", 0)

    if not generated_code:
        raise ValueError("Generated code is empty, cannot execute")

    if not input_file_path:
        raise ValueError("Input file path is empty")

    # 2. Read dirty data
    print(f"[INFO] Reading dirty data: {input_file_path}")
    try:
        df = pd.read_csv(input_file_path, encoding="utf-8-sig")
        print(f"[SUCCESS] Data loaded successfully: {df.shape}")
    except Exception as e:
        error_msg = f"Failed to read input file: {str(e)}"
        print(f"[ERROR] {error_msg}")
        return {
            "execution_success": False,
            "execution_error": error_msg,
            "execution_history": [{
                "attempt": retry_count + 1,
                "error": error_msg,
                "stage": "data_loading"
            }]
        }

    # 3. Execute code (sandbox mode)
    print(f"\n[INFO] Executing code in sandbox...")
    print(f"   Attempt number: {retry_count + 1}")

    try:
        # Create isolated namespace
        namespace = {
            "pd": pd,
            "np": __import__("numpy"),
            "datetime": __import__("datetime"),
            "re": __import__("re"),
        }

        # Execute code (load clean_data function into namespace)
        exec(generated_code, namespace)

        # Extract clean_data function
        if "clean_data" not in namespace:
            raise ValueError("clean_data function not found in generated code")

        clean_data_func = namespace["clean_data"]

        # Execute cleaning
        print("   [INFO] Executing clean_data(df)...")
        cleaned_df = clean_data_func(df)

        # Validate return value
        if not isinstance(cleaned_df, pd.DataFrame):
            raise TypeError(
                f"clean_data function returned wrong type: "
                f"expected pd.DataFrame, got {type(cleaned_df)}"
            )

        print(f"[SUCCESS] Code executed successfully!")
        print(f"   Original data: {df.shape}")
        print(f"   After cleaning: {cleaned_df.shape}")

        # 🔍 DEBUG: Print per-column missing values for debugging
        print("\n" + "="*60)
        print("--- DEBUG: MISSING VALUES PER COLUMN AFTER CLEANING ---")
        print("="*60)
        missing_per_col = cleaned_df.isna().sum()
        for col, count in missing_per_col.items():
            if count > 0:
                print(f"  {col}: {count} missing values")
        print(f"  TOTAL MISSING: {missing_per_col.sum()}")
        print("="*60 + "\n")

        # 4. Save cleaned data
        output_path = Path(output_file_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        cleaned_df.to_csv(output_file_path, index=False, encoding="utf-8-sig")
        print(f"[SUCCESS] Cleaned data saved: {output_file_path}")

        # 5. Extract cleaned data metadata
        cleaned_df_info = extract_df_info(cleaned_df)

        # 6. Print comparison information
        print("\n" + "-"*60)
        print("Data Cleaning Effect Comparison:")
        print("-"*60)
        original_info = state.get("original_df_info", {})
        print_comparison(original_info, cleaned_df_info)

        # 7. Return success state
        return {
            "execution_success": True,
            "execution_error": None,
            "cleaned_df_info": cleaned_df_info,
            "execution_history": [{
                "attempt": retry_count + 1,
                "error": None,
                "stage": "success",
                "shape_before": df.shape,
                "shape_after": cleaned_df.shape
            }]
        }

    except Exception as e:
        # 8. Capture exception
        error_traceback = traceback.format_exc()
        error_summary = str(e)

        print(f"\n[ERROR] Code execution failed!")
        print(f"   Error type: {type(e).__name__}")
        print(f"   Error message: {error_summary}")
        print(f"\nComplete Traceback:")
        print("-"*60)
        print(error_traceback)
        print("-"*60)

        # 9. Return failure state
        return {
            "execution_success": False,
            "execution_error": error_traceback,
            "execution_history": [{
                "attempt": retry_count + 1,
                "error": error_summary,
                "stage": "code_execution"
            }]
        }


# ========== Helper Functions ==========
def extract_df_info(df: pd.DataFrame) -> Dict[str, Any]:
    """
    Extract DataFrame metadata

    Args:
        df: Pandas DataFrame

    Returns:
        Dictionary containing metadata
    """
    # Missing value statistics
    null_counts = df.isnull().sum().to_dict()
    total_nulls = sum(null_counts.values())

    # Missing values per column (explicit for QA node visibility)
    missing_values = df.isna().sum().to_dict()

    # Data types (explicit conversion to string for QA node)
    dtypes = df.dtypes.astype(str).to_dict()

    # Sample data (first 10 rows)
    sample_data = df.head(10).to_string()

    # Memory usage
    memory_usage = df.memory_usage(deep=True).sum()
    memory_mb = memory_usage / (1024 * 1024)

    return {
        "shape": df.shape,
        "columns": df.columns.tolist(),
        "dtypes": dtypes,
        "missing_values": missing_values,  # Explicit field for QA verification
        "null_counts": null_counts,  # Keep for backward compatibility
        "total_nulls": total_nulls,
        "sample_data": sample_data,
        "memory_usage": f"{memory_mb:.2f} MB",
        "duplicate_count": df.duplicated().sum(),
    }


def print_comparison(original_info: Dict[str, Any], cleaned_info: Dict[str, Any]) -> None:
    """
    Print before/after comparison information

    Args:
        original_info: Original data metadata
        cleaned_info: Cleaned data metadata
    """
    print(f"  Row count: {original_info.get('shape', ['?'])[0]} -> {cleaned_info.get('shape', ['?'])[0]}")
    print(f"  Column count: {original_info.get('shape', [0, '?'])[1]} -> {cleaned_info.get('shape', [0, '?'])[1]}")

    original_nulls = original_info.get("total_nulls", 0)
    cleaned_nulls = cleaned_info.get("total_nulls", 0)
    null_reduction = original_nulls - cleaned_nulls

    print(f"  Missing values: {original_nulls} -> {cleaned_nulls} (reduced by {null_reduction})")

    original_dups = original_info.get("duplicate_count", 0)
    cleaned_dups = cleaned_info.get("duplicate_count", 0)
    dup_reduction = original_dups - cleaned_dups

    print(f"  Duplicate rows: {original_dups} -> {cleaned_dups} (reduced by {dup_reduction})")


def validate_execution_safety(code: str) -> bool:
    """
    Validate code safety (pre-execution check)

    Args:
        code: Code to be executed

    Returns:
        Whether safety check passed
    """
    import re

    # Dangerous operation patterns
    dangerous_patterns = [
        r"\beval\(",           # Prohibit eval
        r"\bexec\(",           # Prohibit nested exec
        r"\b__import__\(",     # Prohibit dynamic import
        r"os\.system",         # Prohibit system calls
        r"subprocess\.",       # Prohibit subprocess
        r"open\(",             # Prohibit file operations (except pandas)
        r"\.to_csv\(",         # Prohibit file writing
        r"\.to_excel\(",       # Prohibit Excel writing
    ]

    for pattern in dangerous_patterns:
        if re.search(pattern, code):
            print(f"[WARNING] Safety check failed: dangerous operation found {pattern}")
            return False

    return True
